#!/usr/bin/env bash
# Stop hook — push any unpushed commits to origin automatically at end of turn.
#
# Why: the git workflow says push as work lands; relying on the model to remember
# (and not ask) is unreliable. This makes it deterministic. It only pushes work that
# is ALREADY COMMITTED — it never creates commits. The `trunk` dev trunk and any
# feature branches get pushed; `main` is EXCLUDED (it is a generated build artifact,
# pushed only by scripts/publish_main.sh). No-ops safely until an `origin` remote and
# an upstream exist. Failures are non-fatal (exit 0) so it never blocks -- but they print
# git's ACTUAL stderr, never a bare "FAILED": a swallowed error here once hid 123 unpushed
# commits for 27 days (no known_hosts entry for github.com), which is exactly the failure a
# silent hook is worst at.
set -uo pipefail
REPO="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO" 2>/dev/null || exit 0

# No remote yet -> nothing to do (repo not published).
git remote get-url origin >/dev/null 2>&1 || exit 0

git worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2}' | while read -r wt; do
  br=$(git -C "$wt" symbolic-ref --quiet --short HEAD 2>/dev/null) || continue
  [ -z "$br" ] && continue
  [ "$br" = "main" ] && continue   # main is generated by scripts/publish_main.sh, never auto-pushed

  if git -C "$wt" rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    ahead=$(git -C "$wt" rev-list --count '@{u}'..HEAD 2>/dev/null || echo 0)
    if [ "${ahead:-0}" -gt 0 ]; then
      if err=$(git -C "$wt" push --quiet 2>&1); then
        echo "[auto-push] $br: pushed $ahead commit(s) to origin"
      else
        echo "[auto-push] $br: push of $ahead commit(s) FAILED -- commits are NOT on origin"
        echo "[auto-push]   local:  ${err:-(no output)}"
      fi
    fi
  else
    if err=$(git -C "$wt" push --quiet -u origin "$br" 2>&1); then
      echo "[auto-push] $br: published new branch to origin"
    else
      echo "[auto-push] $br: publish of '$br' FAILED -- branch is NOT on origin"
      echo "[auto-push]   ${err:-(no output)}"
    fi
  fi
done
exit 0
